(function () {
    "use strict";

    var csInterface = new CSInterface();

    // ---------------------------------------------------------------
    // Host bridge
    // ---------------------------------------------------------------
    function callHost(fnName, paramsObj) {
        return new Promise(function (resolve) {
            var script = paramsObj !== undefined
                ? fnName + "(" + JSON.stringify(JSON.stringify(paramsObj)) + ")"
                : fnName + "()";
            csInterface.evalScript(script, function (result) {
                if (!result) { resolve({ ok: false, error: "No response from After Effects." }); return; }
                try { resolve(JSON.parse(result)); }
                catch (e) { resolve({ ok: false, error: "Bad response: " + result }); }
            });
        });
    }

    function $(id) { return document.getElementById(id); }

    var el = {
        btnRefresh: $("btnRefresh"),
        btnHelp: $("btnHelp"),
        statusDot: $("statusDot"),
        statusText: $("statusText"),

        compEmpty: $("compEmpty"),
        compInfo: $("compInfo"),
        compName: $("compName"),
        compMeta: $("compMeta"),

        rolesEmpty: $("rolesEmpty"),
        rolesList: $("rolesList"),
        rolesActions: $("rolesActions"),
        btnSaveRoles: $("btnSaveRoles"),

        modeFit: $("modeFit"),
        modeStack: $("modeStack"),
        cbRecursePrecomps: $("cbRecursePrecomps"),
        cbSafeZones: $("cbSafeZones"),
        cbLiveText: $("cbLiveText"),
        cbResync: $("cbResync"),

        btnReframe: $("btnReframe"),
        resultsEmpty: $("resultsEmpty"),
        resultsList: $("resultsList"),

        namingTemplate: $("namingTemplate"),
        btnQueueRender: $("btnQueueRender"),

        btnAudit: $("btnAudit"),
        auditEmpty: $("auditEmpty"),
        auditList: $("auditList"),

        helpOverlay: $("helpOverlay")
    };

    var state = {
        comp: null,
        layers: [],
        roles: ["background", "headline", "lower-third", "bug", "ots", "foreground", "unassigned"],
        lastResults: []
    };

    function setStatus(msg, kind) {
        el.statusText.textContent = msg;
        el.statusText.className = "status-text" + (kind ? " " + kind : "");
        el.statusDot.className = "status-dot" + (kind ? " " + kind : "");
    }

    function escapeHtml(s) {
        return String(s == null ? "" : s).replace(/[&<>"']/g, function (c) {
            return { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c];
        });
    }

    // ---------------------------------------------------------------
    // Refresh — load active comp + its top-level layers
    // ---------------------------------------------------------------
    function refresh() {
        setStatus("Reading active composition…", "scanning");
        callHost("csGetActiveCompInfo").then(function (res) {
            if (!res.ok) {
                state.comp = null;
                el.compEmpty.style.display = "block";
                el.compEmpty.textContent = res.error || "No active composition.";
                el.compInfo.style.display = "none";
                el.rolesEmpty.style.display = "block";
                el.rolesList.style.display = "none";
                el.rolesActions.style.display = "none";
                setStatus(res.error || "No active composition.", "warning");
                return;
            }
            state.comp = res.comp;
            state.layers = res.layers;
            state.roles = res.roles;

            el.compEmpty.style.display = "none";
            el.compInfo.style.display = "block";
            el.compName.textContent = res.comp.name;
            el.compMeta.textContent = res.comp.width + "×" + res.comp.height +
                " · " + res.comp.aspectClass +
                (res.alreadyGenerated ? " · previously generated by Auto Reframe" : "");

            renderRoles();
            setStatus("Loaded \"" + res.comp.name + "\" (" + res.layers.length + " top-level layer(s)).", "success");
        });
    }
    el.btnRefresh.addEventListener("click", refresh);

    // ---------------------------------------------------------------
    // Element roles list
    // ---------------------------------------------------------------
    function renderRoles() {
        if (state.layers.length === 0) {
            el.rolesEmpty.style.display = "block";
            el.rolesEmpty.textContent = "This comp has no top-level layers.";
            el.rolesList.style.display = "none";
            el.rolesActions.style.display = "none";
            return;
        }
        el.rolesEmpty.style.display = "none";
        el.rolesList.style.display = "block";
        el.rolesActions.style.display = "flex";
        el.rolesList.innerHTML = "";

        state.layers.forEach(function (layer) {
            var row = document.createElement("div");
            row.className = "row-item role-row";

            var tags = [];
            if (layer.isPrecomp) tags.push("precomp");
            if (layer.isCamera) tags.push("camera");
            if (layer.isThreeD) tags.push("3D");
            if (layer.locked) tags.push("locked");

            var label = document.createElement("div");
            label.className = "role-row-label";
            label.innerHTML = '<span class="role-row-name">' + escapeHtml(layer.name) + '</span>' +
                (tags.length ? '<span class="role-row-tags">' + tags.join(" · ") + '</span>' : "");

            var select = document.createElement("select");
            select.className = "role-select";
            select.dataset.layerIndex = layer.index;
            state.roles.forEach(function (r) {
                var opt = document.createElement("option");
                opt.value = r;
                opt.textContent = r;
                if (r === layer.role) opt.selected = true;
                select.appendChild(opt);
            });

            row.appendChild(label);
            row.appendChild(select);
            el.rolesList.appendChild(row);
        });
    }

    el.btnSaveRoles.addEventListener("click", function () {
        var selects = el.rolesList.querySelectorAll(".role-select");
        var assignments = [];
        selects.forEach(function (s) {
            assignments.push({ layerIndex: parseInt(s.dataset.layerIndex, 10), role: s.value });
        });
        setStatus("Saving element roles…", "scanning");
        callHost("csAssignRoles", { assignments: assignments }).then(function (res) {
            if (res.ok) setStatus("Saved roles on " + res.applied + " layer(s).", "success");
            else setStatus(res.error || "Could not save roles.", "error");
        });
    });

    // ---------------------------------------------------------------
    // Generate formats
    // ---------------------------------------------------------------
    function gatherReframeParams() {
        var presets = [];
        document.querySelectorAll(".cbFormat:checked").forEach(function (cb) { presets.push(cb.value); });
        return {
            presets: presets,
            mode: el.modeStack.checked ? "stack" : "fit",
            recursePrecomps: el.cbRecursePrecomps.checked,
            safeZoneGuides: el.cbSafeZones.checked,
            liveTextLink: el.cbLiveText.checked,
            resync: el.cbResync.checked
        };
    }

    function renderResults(results, errors) {
        state.lastResults = results || [];
        if (state.lastResults.length === 0 && (!errors || errors.length === 0)) {
            el.resultsEmpty.style.display = "block";
            el.resultsList.style.display = "none";
            return;
        }
        el.resultsEmpty.style.display = "none";
        el.resultsList.style.display = "block";
        el.resultsList.innerHTML = "";

        state.lastResults.forEach(function (r) {
            var row = document.createElement("div");
            row.className = "row-item";
            row.innerHTML = '<span class="row-word">' + escapeHtml(r.compName) + '</span>' +
                '<span class="row-count">' + escapeHtml(r.presetLabel) + '</span>';
            el.resultsList.appendChild(row);
        });
        (errors || []).forEach(function (e) {
            var row = document.createElement("div");
            row.className = "row-item";
            row.innerHTML = '<span class="row-word error-text">' + escapeHtml(e.presetKey) + ' failed</span>' +
                '<span class="row-count">' + escapeHtml(e.error) + '</span>';
            el.resultsList.appendChild(row);
        });
    }

    el.btnReframe.addEventListener("click", function () {
        var params = gatherReframeParams();
        if (params.presets.length === 0) { setStatus("Pick at least one target format.", "warning"); return; }
        el.btnReframe.disabled = true;
        setStatus("Generating " + params.presets.length + " format(s)…", "scanning");
        callHost("csReframe", params).then(function (res) {
            el.btnReframe.disabled = false;
            if (!res.ok) { setStatus(res.error || "Reframe failed.", "error"); return; }
            renderResults(res.results, res.errors);
            var okCount = res.results.length, failCount = (res.errors || []).length;
            if (failCount === 0) setStatus("Generated " + okCount + " comp(s).", "success");
            else setStatus("Generated " + okCount + " comp(s), " + failCount + " failed — see Results.", "warning");
        });
    });

    // ---------------------------------------------------------------
    // Render queue
    // ---------------------------------------------------------------
    el.btnQueueRender.addEventListener("click", function () {
        if (state.lastResults.length === 0) { setStatus("Generate formats first.", "warning"); return; }
        var compIds = state.lastResults.map(function (r) { return r.compId; });
        setStatus("Queuing " + compIds.length + " comp(s) for render…", "scanning");
        callHost("csQueueRender", { compIds: compIds, namingTemplate: el.namingTemplate.value }).then(function (res) {
            if (!res.ok) { setStatus(res.error || "Could not queue render.", "error"); return; }
            setStatus("Queued " + res.queued.length + " comp(s) in the Render Queue.", "success");
        });
    });

    // ---------------------------------------------------------------
    // Audit
    // ---------------------------------------------------------------
    function severityClass(sev) {
        if (sev === "warning") return "warning";
        if (sev === "error") return "error";
        return "";
    }

    el.btnAudit.addEventListener("click", function () {
        setStatus("Auditing active comp…", "scanning");
        callHost("csAudit").then(function (res) {
            if (!res.ok) { setStatus(res.error || "Audit failed.", "error"); return; }
            if (res.findings.length === 0) {
                el.auditEmpty.style.display = "block";
                el.auditList.style.display = "none";
                setStatus("Audit clean — no issues flagged.", "success");
                return;
            }
            el.auditEmpty.style.display = "none";
            el.auditList.style.display = "block";
            el.auditList.innerHTML = "";
            res.findings.forEach(function (f) {
                var row = document.createElement("div");
                row.className = "row-item location-item";
                row.innerHTML = '<div class="src ' + severityClass(f.severity) + '">' + escapeHtml(f.type) + '</div>' +
                    '<div class="label">' + escapeHtml(f.layer) + '</div>' +
                    '<div class="label" style="color:var(--muted);">' + escapeHtml(f.detail) + '</div>';
                el.auditList.appendChild(row);
            });
            setStatus(res.count + " issue(s) flagged — informational, nothing was changed.", "warning");
        });
    });

    // ---------------------------------------------------------------
    // Help overlay
    // ---------------------------------------------------------------
    function openOverlay(id) { $(id).classList.add("open"); }
    document.querySelectorAll("[data-close]").forEach(function (btn) {
        btn.addEventListener("click", function () { $(btn.getAttribute("data-close")).classList.remove("open"); });
    });
    el.helpOverlay.addEventListener("click", function (e) { if (e.target === el.helpOverlay) el.helpOverlay.classList.remove("open"); });
    el.btnHelp.addEventListener("click", function () { openOverlay("helpOverlay"); });

    // ---------------------------------------------------------------
    // Init
    // ---------------------------------------------------------------
    function init() {
        callHost("csGetInfo").then(function (res) {
            if (res.ok) {
                $("appTitle").textContent = res.appName;
                $("appByline").textContent = "by " + res.author + " · v" + res.version;
                if (!res.hasProject) { setStatus("Open an After Effects project to get started.", "warning"); return; }
                refresh();
            }
        });
    }

    init();
})();
